language: ruby

services:
  - postgresql

addons:
  postgresql: "9.4"

rvm:
  - 2.5.1

before_script:
  - psql -c 'create database "re-birth_test";' -U postgres
  - cp .env.test.local.travis .env.test.local

branches:
  only:
  - master
  - develop
  - release

env:
  global:
    - RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1 && ./autogen.sh && ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh && make && ./tests && sudo make install && cd ..
  - bundle install
  - nvm install 8.11.2
  - node -v
  - npm i -g yarn
  - yarn

# run code quality audit
before_script:
  - gem install code_quality --no-ri --no-rdoc
  - code_quality security_audit
  - code_quality quality_audit fail_fast=false generate_index=true lowest_score=89 rubocop_max_offenses=400

script:
  - bundle exec rails db:migrate
  - bundle exec rails spec

after_success:
  - bash <(curl -s https://codecov.io/bash)
